// <auto-generated />
using System;
using Cosmos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cosmos.Data.Migrations
{
    [DbContext(typeof(CosmosDataContext))]
    partial class CosmosDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("Cosmos.Data.PriceList", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateAdded");

                    b.Property<DateTime>("validUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validUntil");

                    b.HasKey("id");

                    b.ToTable("Pricelist");
                });
#pragma warning restore 612, 618
        }
    }
}
